server:
  port: 8000

spring:
  application:
    name: novel-admin

  profiles:
    active: local
  config:
    import:
      - optional:nacos:novel-admin-local.yaml?group=DEFAULT_GROUP&refreshEnabled=true
  cloud:
    nacos:
      config:
        namespace:
        group: DEFAULT_GROUP
        file-extension: yaml

      discovery:
        namespace:
        group: DEFAULT_GROUP